services:
  - type: web
    name: anxiety-detection-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        value: changethis32characterslongkey123
      - key: STRIPE_SECRET_KEY
        value: sk_test_placeholder